services:
  - type: web
    name: blog-app
    env: docker
    repo: https://github.com/hyeon924/blog
    region: singapore
    branch: main
    dockerfilePath: back/Dockerfile
    buildCommand: "./gradlew build -x test"
    startCommand: "java -jar app.jar"
    rootDir: back
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: secret
      - key: JWT_SECRET
        value: dfkjsalfjkasluifjhe4rlkifjnaslkdjfj93flaskfmlaskf2$Rdkjfalsdfkjasfldkjasflkjasfas52df4a5sf4$#%rnslckjnsldfkjaslfkjasl,kfjauysi3eurnasfjkl4irualmfnla34uraolwf4rkosfml
      - key: DB_HOST
        value: dpg-d1bbrdodl3ps73eh8m80-a
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: blog_postgres_udm0
      - key: DB_USERNAME
        value: blog_postgres_udm0_user
      - key: DB_PASSWORD
        value: ucJyZJdzxuo0Up079SMuJhwdyOxtd8PU
      - key: EMAIL_USERNAME
        value: hyeonn4713@gmail.com
      - key: EMAIL_PASSWORD
        value: anup azyn jjhd gfpn
